name: Cron

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 */2 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          envkey_REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: |
          cat info-schema.json
          ls -la .
      - run: node main.js
      - run: |
          git config --global user.name 'EE UR'
          git add .
          git commit -m "Update data at $(date)"
          git push
      - run: |
          cat info-schema.json
          ls -la .
